/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_aboutdialog1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_messagebox (char *BoxName, char *CallShow,int i);
GtkWidget* create_windowc (char *BoxName, char *CallShow,int i);
GtkWidget* create_window3 (void);
