/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "../pixmaps/logo.xpm"
#include "../pixmaps/connecting.xpm"
#include "../pixmaps/MyNet.xpm"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget *CreateWidgetFromXpm (GtkWidget * parent, gchar ** xpm_data);

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *fixed1;
  GtkWidget *hseparator1;

  GtkWidget *label1;

  GtkWidget *label2;
	
  GtkWidget *image1;
  GtkWidget *button3;
  GtkWidget *button2;
  GtkWidget *button1;
	
  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, -1, 276);
  gtk_window_set_title (GTK_WINDOW (window1), _("MyNet"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 500, 398);
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);
  window1_icon_pixbuf = gdk_pixbuf_new_from_xpm_data((gchar **)MyNet_xpm);
	//create_pixbuf ("../pixmaps/MyNet.png");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }
  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 0, 128);
  gtk_widget_set_size_request (hseparator1, 286, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 80, 144);
  gtk_widget_set_size_request (entry1, 158, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label1 = gtk_label_new (_("\347\224\250\346\210\267\345\220\215"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 40, 152);
  gtk_widget_set_size_request (label1, 39, 17);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 80, 184);
  gtk_widget_set_size_request (entry2, 158, 25);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);

  label2 = gtk_label_new (_("\345\257\206    \347\240\201"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 40, 192);
  gtk_widget_set_size_request (label2, 39, 17);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("\350\256\260\344\275\217\345\257\206\347\240\201"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 80, 216);
  gtk_widget_set_size_request (checkbutton1, 100, 21);
  
  gtk_widget_realize (window1);
  image1=CreateWidgetFromXpm (window1, (gchar **)logo_xpm);
  
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 286, 136);

  button3 = gtk_button_new_with_mnemonic (_("\345\261\236\346\200\247"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 200, 240);
  gtk_widget_set_size_request (button3, 53, 27);

  button2 = gtk_button_new_with_mnemonic (_("\351\200\200\345\207\272"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 136, 240);
  gtk_widget_set_size_request (button2, 53, 27);

  button1 = gtk_button_new_with_mnemonic (_("\350\277\236\346\216\245"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 72, 240);
  gtk_widget_set_size_request (button1, 53, 27);
  g_signal_connect (G_OBJECT (window1), "delete_event",
		      G_CALLBACK (delete_event), NULL);
	  
  g_signal_connect ((gpointer) window1, "show",
                    G_CALLBACK (on_window1_show),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (before_quit),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  return window1;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "cc0cc@126.com",
	"xdkui@163.com",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *aboutdialog1_logo_pixbuf;

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), _("MyNet"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), _("copyright 2006 cc0cc"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog1), _("\345\243\260\346\230\216\357\274\232MyNet\346\230\257\344\273\245\347\240\224\347\251\266\345\222\214\345\255\246\344\271\240\344\270\272\347\233\256\347\232\204\345\274\200\345\217\221\347\232\204\357\274\214\346\210\221\344\273\254\346\211\200\345\201\232\347\232\204\344\270\200\345\210\207\351\203\275\351\201\265\345\276\252\344\270\255\345\215\216\344\272\272\346\260\221\345\205\261\345\222\214\345\233\275\343\200\212\350\256\241\347\256\227\346\234\272\350\275\257\344\273\266\344\277\235\346\212\244\346\235\241\344\276\213\343\200\213\343\200\202\n\345\246\202\346\236\234\344\275\240\345\234\250\345\255\246\344\271\240\350\277\207\347\250\213\344\270\255\351\234\200\350\246\201\346\255\244\350\275\257\344\273\266\357\274\214\350\257\267\345\210\260cc0cc.126.com\346\217\220\344\272\244\344\275\240\347\232\204\345\206\205\347\275\221IP\345\222\214E-mail"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog1), translators);
  aboutdialog1_logo_pixbuf = gdk_pixbuf_new_from_xpm_data((gchar **)MyNet_xpm);
  //create_pixbuf ("../pixmaps/MyNet.png");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (aboutdialog1), aboutdialog1_logo_pixbuf);
  if (aboutdialog1_logo_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (aboutdialog1), aboutdialog1_logo_pixbuf);
      gdk_pixbuf_unref (aboutdialog1_logo_pixbuf);
    }
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GdkPixbuf *window2_icon_pixbuf;
  GtkWidget *fixed2;

  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *label5;

  GtkWidget *button4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label6;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 274, 200);
  gtk_window_set_title (GTK_WINDOW (window2), _("获取服务"));
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);
  //window2_icon_pixbuf = create_pixbuf ("../pixmaps/connecting.png");
  window2_icon_pixbuf =gdk_pixbuf_new_from_xpm_data((gchar **)connecting_xpm);
	if (window2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window2), window2_icon_pixbuf);
      gdk_pixbuf_unref (window2_icon_pixbuf);
    }

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);
  gtk_widget_set_size_request (fixed2, 238, 121);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 80, 16);
  gtk_widget_set_size_request (entry3, 158, 25);
  gtk_editable_set_editable (GTK_EDITABLE (entry3), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 80, 56);
  gtk_widget_set_size_request (entry4, 158, 25);
  gtk_editable_set_editable (GTK_EDITABLE (entry4), TRUE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label4 = gtk_label_new (_("\346\234\215\345\212\241\345\231\250"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 32, 64);
  gtk_widget_set_size_request (label4, 47, 17);

  label3 = gtk_label_new (_("ip\345\234\260\345\235\200"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 40, 24);
  gtk_widget_set_size_request (label3, 34, 17);

  label5 = gtk_label_new (_("mac"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 32, 96);
  gtk_widget_set_size_request (label5, 34, 17);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 80, 96);
  gtk_widget_set_size_request (comboboxentry1, 158, 25);
  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 104, 144);
  gtk_widget_set_size_request (button4, 85, 27);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button4), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("\350\216\267\345\217\226\346\234\215\345\212\241"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) window2, "show",
                    G_CALLBACK (on_window2_show),
                    NULL);
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, image2, "image2");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");

  return window2;
}

GtkWidget *
CreateWidgetFromXpm (GtkWidget * parent, gchar ** xpm_data)
{
        GdkBitmap *mask;
        GdkPixmap *pixmap_data;
        GtkWidget *pixmap_widget;

        pixmap_data = gdk_pixmap_create_from_xpm_d (parent->window,
                                                    &mask,
                                                    NULL,
                                                    (gchar **) xpm_data);
        pixmap_widget = gtk_pixmap_new (pixmap_data, mask);
        gtk_widget_show (pixmap_widget);

        return (pixmap_widget);
}

GtkWidget*
create_messagebox (char *BoxName, char *CallShow, int i)
{
 create_windowc ((char *)BoxName, (char *)CallShow,(int)i);
}

GtkWidget*
create_windowc (char *BoxName, char *CallShow,int i)
{
  GtkWidget *windowc;
  GdkPixbuf *windowc_icon_pixbuf;
  GtkWidget *fixed2;
  GtkWidget *label4;
  GtkWidget *button1;

  windowc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowc, 260, 90);
  gtk_window_set_title (GTK_WINDOW (windowc), _(BoxName));
  gtk_window_set_resizable (GTK_WINDOW (windowc), FALSE);
  windowc_icon_pixbuf =gdk_pixbuf_new_from_xpm_data((gchar **)connecting_xpm);
  if (windowc_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (windowc), windowc_icon_pixbuf);
      gdk_pixbuf_unref (windowc_icon_pixbuf);
    }

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowc), fixed2);

  label4 = gtk_label_new (_(CallShow));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 24, 0);
  gtk_widget_set_size_request (label4, 197, 57);

  button1 = gtk_button_new_with_mnemonic (_("\347\241\256\345\256\232\n"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 96, 56);
  gtk_widget_set_size_request (button1, 55, 29);

if(i==1){
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (delete_getAtrBox),
                    NULL);
}else if(i==0){
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
	}

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowc, windowc, "window2");
  GLADE_HOOKUP_OBJECT (windowc, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowc, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowc, button1, "button1");

  return windowc;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GdkPixbuf *window3_icon_pixbuf;
  GtkWidget *fixed3;
  GtkWidget *label5;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window3, 236, 122);
  gtk_window_set_title (GTK_WINDOW (window3), _("\346\263\250\345\206\214\350\277\233\350\241\214\344\270\255"));
  gtk_window_set_resizable (GTK_WINDOW (window3), FALSE);
  window3_icon_pixbuf = gdk_pixbuf_new_from_xpm_data((gchar **)connecting_xpm);
  if (window3_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window3), window3_icon_pixbuf);
      gdk_pixbuf_unref (window3_icon_pixbuf);
    }

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  label5 = gtk_label_new (_("\346\263\250\345\206\214\350\277\233\350\241\214\344\270\255\357\274\214\350\257\267\347\250\215\345\200\231\343\200\202\343\200\202\343\200\202"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 24, 40);
  gtk_widget_set_size_request (label5, 200, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, label5, "label5");

  return window3;
}
