/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#define SERVER "192.168.254.253"
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include <gnome.h>
#include "tray.h"

#undef Q_
#ifdef ENABLE_NLS
#  define Q_(String) g_strip_context ((String), gettext (String))
#else
#  define Q_(String) g_strip_context ((String), (String))
#endif
// typedef char BYTE; 
/*
 * Public Functions.
 */
 /*公有的控件，用来获取数据 */
  GtkWidget *window1;
  GtkWidget *linkwindow;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *checkbutton1;
  GtkWidget *comboboxentry1;
  GtkWidget *getAtrBox;
  tray_demo *tray;
 /*====================*/


/*
 * This function returns a widget in a component created by Glade.
 * Call it with the toplevel widget in the component (i.e. a window/dialog),
 * or alternatively any widget in the component, and the name of the widget
 * you want returned.
 */
GtkWidget*  lookup_widget              (GtkWidget       *widget,
                                        const gchar     *widget_name);



/*
 * Private Functions.
 */

/* This is used to create the pixmaps used in the interface. */
GtkWidget*  create_pixmap              (GtkWidget       *widget,
                                        const gchar     *filename);

/* This is used to create the pixbufs used in the interface. */
GdkPixbuf*  create_pixbuf              (const gchar     *filename);

/* This is used to set ATK action descriptions. */
void        glade_set_atk_action_description (AtkAction       *action,
                                              const gchar     *action_name,
                                              const gchar     *description);
